# Generated by Django 3.0.5 on 2020-05-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(default='contact name', on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
