# Generated by Django 3.0.5 on 2020-05-28 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200528_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='contact',
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
